import Vue from 'vue'
import { Button, Tag, Form, FormItem, Input, Option, Select, OptionGroup, Tree, Dialog, Row, Col, Message, Card, Progress, Table, Dropdown, DropdownMenu, DropdownItem, Tooltip, Badge, MenuItem, Menu, Submenu, MenuItemGroup, Collapse } from 'element-ui'

Vue.use(Button)
Vue.use(Tag)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Option)
Vue.use(Select)
Vue.use(OptionGroup)
Vue.use(Tree)
Vue.use(Dialog)
Vue.use(Row)
Vue.use(Col)
Vue.use(Message)
Vue.prototype.$message = Message
Vue.use(Card)
Vue.use(Progress)
Vue.use(Table)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Tooltip)
Vue.use(Badge)
Vue.use(MenuItem)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(Collapse)
